comment:
  behavior: default

coverage:
  precision: 2
  status:
    project:
      default:
        # basic
        target: 95% #default
        threshold: 0
        base: auto
        flags:
          - unit
        paths:
          - "src"
       # advanced settings
        if_ci_failed: error #success, failure, error, ignore
        informational: false
        only_pulls: false

github_checks:
  annotations: true
