name: documentation

on:
  push:
    branches: [main, 'feature/**']  # branch to trigger deployment

jobs:
  pages:
    runs-on: ubuntu-20.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'  # Specify the required Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install sphinx sphinx_rtd_theme myst_parser  # Install Sphinx and the ReadTheDocs theme
        pip list
        python -c "import sys; print(sys.path)"

    - name: Build Sphinx documentation
      run: |
        sphinx-build docs _build  # Adjust source and destination directories if necessary

    - id: deployment
      name: Deploy to GitHub Pages
      uses: sphinx-notes/pages@v3
